### ISSUE TITLE
Document how to properly distributed Robots and services

### ISSUE THREAD

**Issue by muhamadazmy** [zero-os/0-robot#95] opened 2018-02-21 10:20 UTC
# Scenario:
- Template `X` configures a client `CL`
- Template `Y` retrieves the client with it's name as configured by X (name is CL)

## Case 1: Single node setup
- The scenario works fine, since the local configuration mgmt of the node contains the client config

## Case 2: Multi node setup
- Template X installed on Node 0, hence client is only configured on Node 0
- Template Y installed on Node 1, It can't find the client with name `CL`

# Proposed solution:
A template can define  a special flag (in the class same as the version) which then forces it to be installed on ALL cluster nodes, extra care must be taken when a new node joins the cluster

**Comment by muhamadazmy** [comment] 2018-02-21 13:11
May be also that the service that creates the client config should expose all actions for the required client operations, which means any other service can just call the write action to execute the required task. Unfortunately this will move almost all actions to this single service.

**Comment by zaibon** [comment] 2018-02-22 08:35
Actually this is a non-issue cause this behavior is by design. 
The robot that needs to access certain resource needs to have the proper config, the other one should not. 
Which mean when deploying robot and service we need to be careful that everything is properly distributed and service installed where they should.
So this issue is more like a duplicate of #86 
What could be done on the other hand is better documentation about this concepts.
I'll re-title this issue

**Closed** 2018-05-18 11:04 UTC
Labels: type_bug
